version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: shadowwork-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shadowwork

  server:
    build: ./server
    container_name: shadowwork-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/shadowwork
      - NODE_ENV=production
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: shadowwork-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mongo-data: